const ItemListContainer = () => {
    return (
        <>
            <p>If anyone asks where I am, I've left the country. So, Jonathan, how was the pull-out? No... no El, you're not the monster. You saved me. Do you understand? You saved me. Why do we even need weapons anyway? We have her. I need my paddles! You are such a nerd. No wonder you only hang out with boys.</p>
            <p>Oh... candy, leftovers, Eggo's... she really likes Eggo's. Why do we even need weapons anyway? We have her. Um, I'm happy you're home. We never would've upset you if we knew you had superpowers. I need my paddles! Um, I'm happy you're home. It’s about the shadow monster, isn’t it?</p>
            <p>Just wait till we tell Will that Jennifer Hayes was crying at his funeral. Um, I'm happy you're home. You are such a nerd. No wonder you only hang out with boys. Mornings are for coffee and contemplation. You’re going to take out the demigorgon with a slingshot?</p>
            <p>Nancy, seriously, you're gonna be so cool now, it's ridiculous. You act like you want me to be your friend and then you treat me like garbage. You’re going to be home by 8, listening to the Talking Heads and reading Vonnegut or something. That sounds like a nice night.</p>
            <p>Yeah, I want a date with Bo Derek. We all want things. You act like you want me to be your friend and then you treat me like garbage. You’re pretty cute, you know that? If anyone asks where I am, I've left the country. Nobody normal ever accomplished anything meaningful in this world.</p>
            <p>Um, I'm happy you're home. If anyone asks where I am, I've left the country. Mornings are for coffee and contemplation. Nancy, seriously, you're gonna be so cool now, it's ridiculous. Why do we even need weapons anyway? We have her. We never would've upset you if we knew you had superpowers.</p>
            <p>Do you know anything about sensory deprivation tanks? Specifically how to build one? So, Jonathan, how was the pull-out? You’re going to be home by 8, listening to the Talking Heads and reading Vonnegut or something. That sounds like a nice night. You’re going to take out the demigorgon with a slingshot?</p>
            <p>Don’t take it so personally, okay? I don’t like most people. He’s in the vast majority. Yeah, I want a date with Bo Derek. We all want things. Friends don't lie. YOU BETTER RUN! She's our friend, and she's crazy! Just wait till we tell Will that Jennifer Hayes was crying at his funeral.</p>
            <p>You act like you want me to be your friend and then you treat me like garbage. Why are you keeping this curiosity door lock? Just wait till we tell Will that Jennifer Hayes was crying at his funeral. It's just, sometimes... people don't really say what they're really thinking. But when you capture the right moment, it says more.</p>
            <p>It’s finger-lickin’ good. She shut one door! With her mind! Nobody normal ever accomplished anything meaningful in this world. Do you know anything about sensory deprivation tanks? Specifically how to build one? Um, I'm happy you're home. He’s a sensitive kid. Lonnie used to say he was queer. Called him a fag. Is he? He’s missing, is what he is!</p>
            <p>If anyone asks where I am, I've left the country. So, Jonathan, how was the pull-out? No... no El, you're not the monster. You saved me. Do you understand? You saved me. Why do we even need weapons anyway? We have her. I need my paddles! You are such a nerd. No wonder you only hang out with boys.</p>
            <p>Oh... candy, leftovers, Eggo's... she really likes Eggo's. Why do we even need weapons anyway? We have her. Um, I'm happy you're home. We never would've upset you if we knew you had superpowers. I need my paddles! Um, I'm happy you're home. It’s about the shadow monster, isn’t it?</p>
            <p>Just wait till we tell Will that Jennifer Hayes was crying at his funeral. Um, I'm happy you're home. You are such a nerd. No wonder you only hang out with boys. Mornings are for coffee and contemplation. You’re going to take out the demigorgon with a slingshot?</p>
            <p>Nancy, seriously, you're gonna be so cool now, it's ridiculous. You act like you want me to be your friend and then you treat me like garbage. You’re going to be home by 8, listening to the Talking Heads and reading Vonnegut or something. That sounds like a nice night.</p>
            <p>Yeah, I want a date with Bo Derek. We all want things. You act like you want me to be your friend and then you treat me like garbage. You’re pretty cute, you know that? If anyone asks where I am, I've left the country. Nobody normal ever accomplished anything meaningful in this world.</p>
            <p>Um, I'm happy you're home. If anyone asks where I am, I've left the country. Mornings are for coffee and contemplation. Nancy, seriously, you're gonna be so cool now, it's ridiculous. Why do we even need weapons anyway? We have her. We never would've upset you if we knew you had superpowers.</p>
            <p>Do you know anything about sensory deprivation tanks? Specifically how to build one? So, Jonathan, how was the pull-out? You’re going to be home by 8, listening to the Talking Heads and reading Vonnegut or something. That sounds like a nice night. You’re going to take out the demigorgon with a slingshot?</p>
            <p>Don’t take it so personally, okay? I don’t like most people. He’s in the vast majority. Yeah, I want a date with Bo Derek. We all want things. Friends don't lie. YOU BETTER RUN! She's our friend, and she's crazy! Just wait till we tell Will that Jennifer Hayes was crying at his funeral.</p>
            <p>You act like you want me to be your friend and then you treat me like garbage. Why are you keeping this curiosity door lock? Just wait till we tell Will that Jennifer Hayes was crying at his funeral. It's just, sometimes... people don't really say what they're really thinking. But when you capture the right moment, it says more.</p>
            <p>It’s finger-lickin’ good. She shut one door! With her mind! Nobody normal ever accomplished anything meaningful in this world. Do you know anything about sensory deprivation tanks? Specifically how to build one? Um, I'm happy you're home. He’s a sensitive kid. Lonnie used to say he was queer. Called him a fag. Is he? He’s missing, is what he is!</p>
        </>
    );
};

export default ItemListContainer;